#9
select count(*) from INVOICE;

#10
select count(*) from CUSTOMER where CUS_BALANCEE > 500;

#11
select INVOICE.CUS_CODE, INVOICE.INV_NUMEBR, INVOICE.INV_DATE, PRODUCT.P_DESCRIPT, LINE.LINE_UNITS, LINE.LINE_PRICE
from CUSTOMER, INVOICE, LINE, PRODUCT
where CUSTOMER.CUS_CODE = INVOICE.CUS_CODE 
and INVOICE.INV_NUMBER = LINE.INV_NUMBER
and PRODUCT.P_CODE = LINE.P_CODE
order by INVOCE.CUS_CODE, INVOICE.INV_NUMBER, PRODUCT.P_DESCRIPT;

#12
select INVOICE.CUS_CODE, INVOICE.INV_NUMBER, PRODUCT.P_DESCRIPT, LINE.LINE_UNITS as 'Units Bought', LINE.LINE_PRICE as 'Unit Price', LINE.LINE_UNITS*LINE.LINE_PRICE as Subtotal
from CUSTOMER, INVOICE, LINE, PRODUCT 
where CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
and INVOICE.INV_NUMBER = LINE.INV_NUMBER
and PRODUCT.P_CODE = LINE.P_CODE 
order by INVOICE.CUS_CODE, INVOICE.INV_NUMBER, PRODUCT.P_DESCRIPT; 

#13
select INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE, sum(LINE.LINE_UNITS * LINE.LINE_PRICE) as 'Total Purchases'
from CUSTOMER, INVOICE, LINE
where INVOICE.INV_NUMBER = LINE.INV_NUMBER
and CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
group by INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE; 

#14
select INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE, sum(LINE.LINE_UNITS * LINE.LINE_PRICE) as 'Total Purchases', count(*) as 'Number of Purchases'
from CUSTOMER, INVOICE, LINE
where INVOICE.INV_NUMBER = LINE.INV_NUMBER 
and CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
group by INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE;

#15
select INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE, sum(LINE.LINE_UNITS * LINE.LINE_PRICE) as 'Total Purchases', count(*) as 'Number of Purchases',    avg(LINE.LINE_UNITS * LINE.LINE_PRICE) as 'Average Purchase Amount'
from CUSTOMER, INVOICE, LINE
where INVOICE.INV_NUMBER = LINE.INV_NUMBER
and CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
group by INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE; 

#16
select LINE.INV_NUMBER, sum(LINE.LINE_UNITS * LINE.LINE_PRICE) as 'Invoice Total'
from LINE
group by LINE.INV_NUMBER;

#17
select CUS_CODE, LINE.INV_NUMBER as INV_NUMVER, sum(LINE.LINE_UNITS * LINE.LINE_PRICE) as INV_TOT
from INVOICE, LINE
where INVOICE.INV_NUMBER = LINE.INV_NUMBER
group by CUS_CODE, LINE.INV_NUMBER; 

#18
select CUS_CODE, count(INV_NUMBER) as 'Number of Invoices', avg(INV_TOT) as 'Average Invoice Amount', max(INV_TOT) as 'Max  Invoice Amount',    min(INV_TOT) as 'Min  Invoice Amount', sum(INV_TOT) as 'Total Customer Purchases' 
from (select CUS_CODE, L.INV_NUMBER as INV_NUMBER, sum(L.LINE_UNITS * L.LINE_PRICE) as INV_TOT
from INVOICE I, LINE L
where I.INV_NUMBER = L.INV_NUMBER
group by CUS_CODE, L.INV_NUMBER) as IL
group by CUS_CODE;
