#1
select EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL
from EMPLOYEE
where EMP_LNAME like "smith%";

#2
select PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMPLOYEE.JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
from PROJECT, EMPLOYEE, JOB
where EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM
and JOB.JOB_CODE = EMPLOYEE.JOB_CODE
order by PROJ_VALUE;

#3
select PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMPLOYEE.JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
from PROJECT, EMPLOYEE, JOB
where EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM
and JOB.JOB_CODE = EMPLOYEE.JOB_CODE
order by EMP_LNAME;

#4
select distinct PROJ_NUM
from ASSIGNMENT
order by PROJ_NUM;

#5
select ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE,
ASSIGN_CHG_HR * ASSIGN_HOURS as CACLUATED_ASSIGN_CHARGE
from ASSIGNMENT
order by ASSIGN_NUM;

#6
select ASSIGNMENT.EMP_NUM, EMP_LNAME, sum(ASSIGNMENT.ASSIGN_HOURS) as sumOfASSIGN_HOURS, sum(ASSIGNMENT.ASSIGN_CHG_HR*ASSIGN_HOURS) as sumOfASSIGN_CHARGE from EMPLOYEE, ASSIGNMENT
from EMPLOYEE, ASSIGNMENT
where EMPLOYEE.EMP_NUM = ASSIGNMENT.EMP_NUM
group by ASSIGNMENT.EMP_NUM, EMP_LNAME
order by ASSIGNMENT.EMP_NUM;

#7
select PROJ_NUM,
sum(ASSIGN_HOURS) as sumOfASSIGN_HOURS,
sum(ASSIGN_CHARGE) AS SumOfASSIGN_CHARG
from ASSIGNMENT
group by PROJ_NUM
order by PROJ_NUM;

#8
select SUM(ASSIGN_HOURS) as sumOfASSIGN_HOURS,
sum(ASSIGN_CHARGE) as sumOfASSIGN_CHARGE
from ASSIGNMENT;


